/*
 * EventScriptsDialog.java
 *
 * Created on March 27, 2002, 4:42 PM
 */
package com.johnmunsch.hotsheet;

/**
 *
 * @author  JMunsch
 */
public class EventScriptsDialog extends JCenterableDialog {
    /** Creates new form EventScriptsDialog */
    public EventScriptsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        center(VS_PARENT);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item Store Before Add", "Item Store After Add", "Item Store Before Remove", "Item Store After Remove", "Item Store Before Clear", "Item Store After Clear", "Channel Store Before Add", "Channel Store After Add", "Channel Store Before Remove", "Channel Store After Remove", "Channel Store Before Clear", "Channel Store Before Retrieve", "Channel Store After Retrieve" }));
        getContentPane().add(jComboBox1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton1.setText("Add...");
        jPanel1.add(jButton1);

        jButton2.setText("Remove");
        jPanel1.add(jButton2);

        jButton3.setText("OK");
        jPanel1.add(jButton3);

        jButton4.setText("Cancel");
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JList jList1;
    // End of variables declaration//GEN-END:variables
}
